### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by ghost** [unam3/fsd-rest-news#11]
https://rizzoma.com/topic/c27faf1cfa188c1120f59af4c35e6099/0_b_9n8n_8jl2r/

> Весь код отформатирован через hindent.

Вместо hindent можно использовать любой форматтер: brittany, ormolu, stylish-haskell и др.

**Comment by unam3** [comment]
Есть специальная ветка, ссылку на которую предоставлял в сообщении перед началом ревью: 
https://github.com/unam3/fsd-rest-news/tree/hindented-2

**Comment by ghost** [comment]
Обнови плз мастер тогда, если там неактульная версия

**Comment by unam3** [comment]
Там актуальная версия. Без использования hindent.

**Comment by ghost** [comment]
Зачем иметь две версии? Форматированную и нет?

**Comment by unam3** [comment]
От форматированной вытекают глаза. Читать ее невозможно. Она исключетельно для ревью.

**Comment by ghost** [comment]
В реальных проектах так не работает. Форматтер это удобный унификатор для команды. К сожалению, не всегда он совпадает с твоим любимым представлением кода, но ты его и не один пишешь). Без форматтера все будут писать как они хотят и будет базар вплоть до размера табов. Неужели нет подходящего под твои предпочтения, с достаточной конфигурацией, форматтера?

**Comment by unam3** [comment]
Похоже, что это `stylish-haskell`: https://github.com/unam3/opinionated-haskell-code-formatters-comparison

**Comment by unam3** [comment]
https://github.com/unam3/fsd-rest-news/commit/f617985f7985c71c4ceb2ef8475cdf0ece06fb79
