### ISSUE TITLE
Подключение к БД

### ISSUE THREAD

**Issue by ghost** [unam3/fsd-rest-news#12]
Сейчас в конфиге можно выбрать юзернейм, пароль, бднейм. Но при запуске тестов они падают, потому что конфиг захардкожен в https://github.com/unam3/fsd-rest-news/blob/9d1e93ca0620675d2f5a91b2c50bde03e32ad590/test/RestNewsSpec.hs#L297-L305

**Comment by unam3** [comment]
https://github.com/unam3/fsd-rest-news/commit/c5fbb3d04632817c5558ec419d6b791d71c41bd6
