### ISSUE TITLE
Нетотальные функции

### ISSUE THREAD

**Issue by ghost** [unam3/fsd-rest-news#13]
Нетотальные не стоит использовать, а все исключительные ситуации стоит обрабатывать. `head`, `last`, `init`, `tail`, `fromJust`, etc

**Comment by ghost** [comment]
`error` тоже использовать не стоит. Если уж и кидать эксепншны, то осмысленные (например `SessionErrorThatNeverOccured`), чтобы их потом поймать можно было. Ну и да, их ловить надо, логировать и возвращать соответствующую http ошибку (4xx vs 5xx)

**Comment by unam3** [comment]
В боевом коде все не пойманное логгируется, обрабатывается/пробрасывается дальше с [traplogging](https://hackage.haskell.org/package/hslogger-1.3.1.0/docs/System-Log-Logger.html#v:traplogging) : https://github.com/unam3/fsd-rest-news/blob/a68ebfa1f149fda3878476b9831cc3bdb1cf2d90/src/RestNews.hs#L253
В тестах используется error. Заморачиваться с вбросом исключений в тестах не вижу смысла.

**Comment by ghost** [comment]
Логируется это хорошо, а перебрасывается и что с ней происходит? В какой ответ `SomeException` вообще преобразуется? Можно как то кастомизировать ошибку?

**Comment by ghost** [comment]
Так же заметил использование `exitFailure` внутри треда с обработкой запроса, это никуда не годится

**Comment by unam3** [comment]
> Логируется это хорошо, а перебрасывается и что с ней происходит? В какой ответ `SomeException` вообще преобразуется?

Непойманное отдает 500 Something went wrong.

> Можно как то кастомизировать ошибку?

После логгирования она пробрасывается дальше  — если вообще возможно "кастомизировать ошибку", то да.

**Comment by ghost** [comment]
`createArticleDraft` содержит вызов  `error`
