### ISSUE TITLE
Коды ошибок БД

### ISSUE THREAD

**Issue by ghost** [unam3/fsd-rest-news#17]
Сейчас в качестве кодов ошибок бд используется строка вида   "22001" "2201X" "23503" "23505", что совершенно нечитабельно. В зависимости от этих кодов выполняются разные ветки:
```
           , case getErrorCode sessionResults of
               Just "23503" -> Just "{\"error\": \"such user does not exist\"}"
               Just "23505" ->
                 Just "{\"error\": \"such user is already an author\"}"
               _ -> Nothing)
```
Почему бы не сделать ADT тип с читабельными названиями?

P.S. почему последняя строка `_ -> Nothing`? Что вернется в ответе в этом случае?

**Comment by unam3** [comment]
> почему последняя строка `_ -> Nothing`?

Потому что выбираются ошибки, к которым есть описание для пользователя. Для неучтенных такого описания нет.


> Что вернется в ответе в этом случае?

Пустая строка с почему-то кодом 200.
