### ISSUE TITLE
Типы ошибок

### ISSUE THREAD

**Issue by ghost** [unam3/fsd-rest-news#19]
Ошибки, которые содержаться в `RestNews.DB.Errors` вида:
```
newtype MustNotBeNegative =
    MustNotBeNegative {error :: Text}
        deriving (Show)

instance ToJSON MustNotBeNegative where
    toJSON (MustNotBeNegative error')
        = object ["name" .= error']
```
Не особо имеют смысла. Они все одинаковой структуры (имею ввиду типы, которые ньютайпы над текстом), так же они сразу же используются вместе с `encode` в других местах. Почему нельзя иметь один тип ошибки конечной жсон ошибки?
```
type Error = Error {errror :: Text}
```

P.S. Почему такой странный инстанс `ToJSON`? Почему поле `name`, хотя в типе это `error`? Если там действительно нужен `name` почему бы не использовать его в типе и просто генерить инстанс?

**Comment by unam3** [comment]
> Не особо имеют смысла. … они сразу же используются вместе с encode в других местах

[Минимум надо строить Value, а потом сериализовавать с помощью encode](https://github.com/unam3/fsd-rest-news/issues/14#issue-968749874)


> Почему нельзя иметь один тип ошибки конечной жсон ошибки?

Можно. Из `хорошо бы еще тип _этой_ ошибки иметь` извлек, что для каждой ошибки необходим свой тип.


> P.S. Почему такой странный инстанс ToJSON? Почему поле name, хотя в типе это error?

По пути, видимо, где-то потерял правильное имя поля :)


> почему бы не использовать его в типе и просто генерить инстанс?

Если имеется ввиду автогенерация инстанса без ручного определения toJSON, то
```
 Could not deduce (aeson-1.5.3.0:Data.Aeson.Types.ToJSON.ToJSON
                          RestNews.DB.Errors.WrongUsernameOrPassword)
        arising from a use of ‘encode’
```

**Comment by ghost** [comment]
> > Не особо имеют смысла. … они сразу же используются вместе с encode в других местах
> 
> [Минимум надо строить Value, а потом сериализовавать с помощью encode](https://github.com/unam3/fsd-rest-news/issues/14#issue-968749874)

Но иметь на каждую ошибку новый тип для этого не обязательно. Нет, можно было бы бы иметь по типу, но тогда нет смысла ложить еще внутрь `Text` с каким то текстом ошибки. Т.е.
```haskell
data MustNotBeNegative = MustNotBeNegative

instance ToJSON MustNotBeNegative where
    toJSON (MustNotBeNegative error')
        = object ["error" .= "must not be negative"]
```
имеет смысл, такие ошибки удобно кидать, а задавать ее представление в жсоне можно в инстансе. А вот создавать десяток типов -- оберток над текстом изоморфных друг другу, для того чтобы сериализовать их в одно и то же -- я не вижу в этом смысла

**Comment by ghost** [comment]
> Если имеется ввиду автогенерация инстанса без ручного определения toJSON, то
> 
> ```
>  Could not deduce (aeson-1.5.3.0:Data.Aeson.Types.ToJSON.ToJSON
>                           RestNews.DB.Errors.WrongUsernameOrPassword)
>         arising from a use of ‘encode’
> ```

sooo?
