### ISSUE TITLE
Сделать чистые юнит тесты

### ISSUE THREAD

**Issue by stanislav-az** [unam3/fsd-rest-news#20]
Чистые тесты необходимы для того чтобы научиться абстрагироваться от имплементации и понять как можно прокинуть моковое окружение для тестирования.
Можно попробовать использовать Service Handle [паттерн](https://docs.google.com/document/d/12bwMpwHQklG3YoPlLb8StagMidLYW3CT8Rqvd_El2jA/edit), или mtl-style паттерн проектирования, чтобы потестировать основной функционал сервера.

**Comment by unam3** [comment]
Сделать чистые тесты чего?

Основной функционал сервера уже тестируется с использованием Service Handle паттерн:
https://github.com/unam3/fsd-rest-news/blob/507448e14cecfc6a27131d32f973a2e67c550a10/test/RestNewsSpec.hs#L285-L345

**Comment by stanislav-az** [comment]
Service Handle паттерн используется чтобы абстрагироваться от имплементации. Сейчас тесты не меняют имплементацию: то есть все функции интерпретируются в IO. Чистые юнит тесты подразумевают интерпретацию в другой монаде, к примеру `State Env`.

**Comment by unam3** [comment]
> Service Handle паттерн используется чтобы абстрагироваться от имплементации.

Что и показано в выделенном участке кода — используется своя, тестовая "имплементация" хэндлов, а не боевая.

Что именно необходимо покрыть чистыми тестами так и не ответили.

**Comment by antonkalinin-ml** [comment]
@unam3 закрой пожалуйста issue, оно пока неактуально (у меня нет прав его закрыть). Если понадобится, переоткроем. Стас не занимается ревью, но если передумает, то напишет.
