### ISSUE TITLE
curl скрипты

### ISSUE THREAD

**Issue by ghost** [unam3/fsd-rest-news#21]
Многие скрипты возвращают 404, например, эти:
* `users_getUser` 
* `tags_getTag`
* `tags_createTag`
* `categories_createCategory`

Ответы неоднородные, некоторые возвращают просто строку "No such endpoint", некоторые в теле ничего не возвращают. В идеале бы чтобы все энды возвращали Error json тип, раз уж он есть (например `tags_getTag` так делает)

**Comment by unam3** [comment]
["No such endpoint" error was json-encoded](https://github.com/unam3/fsd-rest-news/commit/b2f495905ad0051cd45bbd58add18be7700569a7)

**Comment by ghost** [comment]
Все еще не получается запустить `users_getUser`, вылетает 404
* В логах никакой информации об ошибках
* Возможно это проблема в аутентификации, у username5 (с которым запускается `users_getUser`) нету админских прав. Можно ли запрашивать этот эндпоинт не админам?

**Comment by ghost** [comment]
Хочется просто позапускать несколько разных скриптов, пополучать красивые ответы (где ничего лишнего не торчит наружу), при этом сильно не париться с построением запросов к твоему АПИ. Понятно дело, пару айдишников может подставить где то надо будет, но будет здорово если об этом из логов понятно станет. В этом плане, решение с сорсингом getCreds отличное. Я сам кому то советовал что то подобное сделать, но забыл что скритпы можно не только запускать, но и сорсить.
