### ISSUE TITLE
Редактирование категории не проверяет на циклы в дереве

### ISSUE THREAD

**Issue by antonkalinin-ml** [unam3/fsd-rest-news#24]
- в базе есть категория с id=2, parent_id = null.
- передаем запрос `PATCH /categories`, боди `{"category_id": 2, "name": "pluh_pattched", "parent_id": 2}`
- запрос завершается успешно, в базе лежит категория, которая ссылается на себя.

При редактировании категории нужно проверять, что в базе не образуются циклы, т.е. что новый родитель не является самой этой категорией или любым ее потомком (не только дочерней, а на любой глубине иерархии). Иначе зациклится или сломается логика выдачи категории (если выдавать ее целиком, со всеми родителями) и логика проверки категории в поиске.

Эти проверки вряд ли получится сделать целиком в базе, нужно будет сделать логику в коде и, может быть, появится желание порефакторить. В этом и смысл - если у нас все делает база, нет особого смысла писать проект на хаскеле :). Хаскель хорош там, где много логики.

**Comment by unam3** [comment]
> Эти проверки вряд ли получится сделать целиком в базе, нужно будет сделать логику в коде

Это проще и правильнее сделать в базе: будет всего один запрос, вместо велосипеда и пляски вокруг двух последовательных с обвязкой на хаскеле.

**Comment by antonkalinin-ml** [comment]
Если получится все сделать в базе, то ок, хотя честно говоря, я бы хотел глянуть на решение в коде :).

- в реальных проектах (у нас, по крайней мере) большая часть логики делается на хаскеле, а не в базе, поэтому было бы здорово попрактиковаться сделать так же. Архитектура проекта не должна этому мешать.
- в базу так или иначе всю логику не запихнешь. Какие-то вещи на PSQL сделать вообще нельзя или очень трудно. Хаскель как язык общего назначения (запросы не берем) намного гибче и удобнее процедурного SQL, соответственно, доработки делать намного проще в хаскеле. Компилятор находит косяки до того, как они выстрелят на проде, чего не скажешь про SQL. Не страшно, если получится больше запросов или они станут медленнее: тормозящие запросы можно точечно оптимизировать по необходимости. Скорость разработки и ясная структура проекта важнее.
- если базу рассматривать только как хранилище, не содержащее логики и закрытое интерфейсом, то легко сменить СУБД, необязательно даже на реляционную.

**Comment by antonkalinin-ml** [comment]
Пожалуйста, оформи эту правку как пулл-реквест для удобства ревью.

**Comment by unam3** [comment]
Когда все сделаю — создам PR с соответствующей ветки. Устроит?

**Comment by antonkalinin-ml** [comment]
А, хорошо. Я думал, уже готово :)

**Comment by unam3** [comment]
Создал PR: https://github.com/unam3/fsd-rest-news/pull/33 . Ревьюй :)
